name: Deploy

on:
  workflow_run:
    workflows:
      - Test
    types:
      - completed
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deploy to environment'
        required: true
        type: environment
        default: 'Stage'

jobs:
  setup-check:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment || 'Stage' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check environment variables
        uses: ./.github/actions/setup-check
        with:
          deploy_host: ${{ secrets.DEPLOY_HOST }}
          deploy_user: ${{ secrets.DEPLOY_USER }}
          deploy_path: ${{ secrets.DEPLOY_PATH }}
          deploy_key: ${{ secrets.DEPLOY_KEY }}

  deploy:
    runs-on: ubuntu-latest
    needs: setup-check
    environment: ${{ inputs.environment || 'Stage' }}
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}

    permissions:
      id-token: write
      contents: read

    env:
      MYENV: ${{ inputs.environment || 'Stage' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy live
        run: |
          echo MYENV=$MYENV
