name: Test

on:
  push:
    branches:
      - main
    paths:
      - 'web/**'
      - 'patches/**'
      - 'scripts/**'
      - 'composer.json'
      - 'composer.lock'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Run tests in environment'
        required: true
        type: environment
        default: 'Stage'
      force-update:
        description: 'Force update of all?'
        type: boolean
        defaultValue: false
      donothing:
        description: 'Do nothing?'
        required: true
        type: boolean
        defaultValue: false

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: My step
        env:
          DOCROOT: ${{ github.workspace }}/web
        if: ${{ ! inputs.donothing }}
        run: |
          if ${{ inputs.force-update }}; then
            echo ALH forced Step ${{ inputs.force-update }}
            ssh $DEPLOY_USER@$DEPLOY_HOST << EOF
            echo yes

          EOF
          else
            echo ALH Step ${{ inputs.force-update }}
          fi
