name: Test

on:
  push:
    branches:
      - main
    paths:
      - 'web/**'
      - 'patches/**'
      - 'scripts/**'
      - 'composer.json'
      - 'composer.lock'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Run tests in environment'
        required: true
        type: environment
        default: 'Stage'
      force-update:
        description: 'Force update of all?'
        type: boolean
        defaultValue: false
      donothing:
        description: 'Do nothing?'
        required: true
        type: boolean
        defaultValue: false

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Init step
        if: ${{ inputs.force-update }}
        run: |
          echo "force-update=true" >> $GITHUB_ENV

      - name: My first step
        if: ${{ env.force-update == 'true' }}
        run: |
          echo first step!

      - name: My step
        if: ${{ ! inputs.donothing || env.force-update == 'true' }}
        run: |
          if ${{ env.force-update == 'true' }}; then
            echo ALH forced Step ${{ inputs.force-update }}
            echo yes
          else
            echo ALH Step ${{ inputs.force-update }}
          fi
